# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'utjamBluetooth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for utjamBluetooth
  pod 'NendSDK_iOS'
  pod 'ReachabilitySwift'
  pod 'MYPassthrough'

  target 'utjamBluetoothTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'utjamBluetoothUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
